### ISSUE TITLE
Add one more step after entering new pin "Confirm Pin" in edit pin

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#117]
Rename steps titles to:

**Set**

- **Set Pin**
   Your pin will be used to unlock your wallet and send money
- **Confirm Pin**
   Your pin will be used to unlock your wallet and send money

**Unlock**

- Enter Pin

**Edit Pin**

- **Edit Pin**
- **New Pin**
- **Confirm New Pin**

if the text does not fit the size of the screen cut and ...

**Comment by mNizhurin** [comment]
done in en localization. Diana notified to make changes in other langs.
