### ISSUE TITLE
adjust how transaction status controller is presented

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#133]
transaction tab >> click on transaction >> click on transaction status cell

The "transaction status" controller should be presented on top of the "transaction info" without collapsing it.

**Comment by rafaelekol** [comment]
We are using `windowAnimationStyle` with
```
android:windowEnterAnimation @anim/slide_in_bottom

android:windowExitAnimation @anim/slide_out_bottom
```
I couldn't find way how to control this animations(to animate and not to animate depending on situation). 
I think we can overcome this animation issue by using Custom Layout with custom show/exit animations

**Comment by rafaelekol** [comment]
Other option is to make FullTransactionInfoView to be a Dialog
