### ISSUE TITLE
 Add App UI Translations:  Turkish & French, Persian

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#181]
- [x] Turkish
- [x] French 
- [x] Persian

**Comment by Dianaaiym** [comment]
added french lang: https://crowdin.com/translate/bank-wallet-android/68/en-fr

**Comment by Dianaaiym** [comment]
added persian lang: https://crowdin.com/project/bank-wallet-android/fa#

**Comment by Dianaaiym** [comment]
added turkish lang https://crowdin.com/translate/bank-wallet-android/68/en-tr
