### ISSUE TITLE
Change IPFS data source URLS to global format

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#197]
Change IPFS requests to request data from global nodes by default and switch to our node only on some timeout value.

The timeout value can be set to twice the average amount of time it takes for requesting data from IPFS. if needed let's have a chat at the time of implementation.

**Comment by rafaelekol** [comment]
I tested some links with via global node, that Nurkaly has given me. Most of the time it was very slow. I consulted with Nurkaly and we decided to postpone this ticket, until he will debug the issue why it takes so long for most of the time.
