### ISSUE TITLE
Apply new Syncing indicators on home tab

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#225]
- [x] Total Balance from old data should be transparent 40%
- [x] If currency rate not available do not show anything 
- [x] Show the percentages instead coin balance on syncing
- [x] Deactivate send button on syncing
- [x] Coin with 0 balance shouldn't affect Total balance state (i.e. if this coin has expired rate, it shouldn't keep total balance color as dimmed)
- [x] Expired rate should have dimmed color also dim color for coin balance
 

on first holder (BTC) show currency rate and syncing state of coin
second (BCH) synced and with not available currency rate
third holder (ETH) synced and with outdated currency rate 

<img width="366" alt="screen shot 2018-11-13 at 2 58 02 pm" src="https://user-images.githubusercontent.com/42367908/48401982-a6697b80-e754-11e8-8b9c-7344b40d35a9.png">

https://zpl.io/aBNXk8e

**Comment by esengulov** [comment]
@TalgatNurdinov removed " Outdated rate should be showed with timestamp"
