### ISSUE TITLE
Add App UI Translations: Chinese, Korean and Spanish

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#234]
- [x] Chinese
- [x] Korean
- [x] Spanish
- [x] @Dianaaiym  identify which languages will be added next and create issue tickets on iOS/Android repos for the next 4 languages. Use following infographics as a reference
![aaf58b5c-e03f-4c1e-990b-d89fbebc6bc7](https://user-images.githubusercontent.com/8611762/48123794-04a1e480-e2a5-11e8-9b7f-cd5d715c358c.jpg)

**Comment by Dianaaiym** [comment]
Added Spanish
https://crowdin.com/project/bank-wallet-android/es-ES#

**Comment by Dianaaiym** [comment]
Added Chinese Simplified
https://crowdin.com/project/bank-wallet-android/zh-CN#

**Comment by Dianaaiym** [comment]
Added Korean
https://crowdin.com/project/bank-wallet-android/ko#
