### ISSUE TITLE
Design Coin Manager

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#243]
- [x] "Add wallets" button on home tab
- [x] Manage wallets in settings (drag / show / hide )
- [x] Add wallets screen (add / remove)

**Comment by esengulov** [comment]
@TalgatNurdinov once controllers are ready upload them here.

@Dianaaiym Localize text strings and list them here along with the design mockups as a reference for @rafaelekol or @omurovch depending on who is going to be implementing this

**Comment by TalgatNurdinov** [comment]
<img width="511" alt="screen shot 2018-12-17 at 4 32 18 pm" src="https://user-images.githubusercontent.com/42367908/50081744-6ac14600-0219-11e9-93f7-ca4c1f6b3074.png">
https://zpl.io/am9B0pQ
