### ISSUE TITLE
Update layout on Welcome screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#258]
let's rework this page a bit

- [ ] design attached
- [ ] the language. should be same to the language set on user's OS. if the language not available on bank wallet then display English.

**Comment by TalgatNurdinov** [comment]
<img width="367" alt="screen shot 2018-12-24 at 3 49 31 pm" src="https://user-images.githubusercontent.com/42367908/50396317-9604e180-0793-11e9-84b5-3e0869bb2020.png">

https://zpl.io/bAvzj5q

**Comment by esengulov** [comment]
@TalgatNurdinov same feedback as on https://github.com/horizontalsystems/bank-wallet-ios/issues/136

**Comment by esengulov** [comment]
@TalgatNurdinov @rafaelekol  the design for welcome screen is work in progress. Pleas redo not start working on the issue unless there is an update below this comment with an updated version of design.

**Comment by TalgatNurdinov** [comment]
https://zpl.io/VQBvOln
<img width="361" alt="screen shot 2019-02-28 at 12 27 25 pm" src="https://user-images.githubusercontent.com/42367908/53545641-58865100-3b54-11e9-8e14-fceb4df7e499.png">
