### ISSUE TITLE
Lock Screen: Send / Receive Controllers

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#277]
We need to provide user with the quick access options to Pay / receive Screens directly from lock screen.

- Receive: same as standard receive controller but should have a coin switcher.

- Pay/Send: should ask for unlock pin/touch before send confirmation controller is shown.

**Comment by TalgatNurdinov** [comment]
<img width="510" alt="screen shot 2018-12-18 at 5 16 58 pm" src="https://user-images.githubusercontent.com/42367908/50150658-d1f9fb80-02e8-11e9-8747-ee9b00ee3384.png">
https://zpl.io/2pndEXy

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/HS-Design/issues/6
