### ISSUE TITLE
Infinite loop using AndroidKeyStore authentication

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android#317]
Saw this issue on phones:
- Xiaomi Mi 5X
- Samsung J3
- LG Nexus 5

https://issuetracker.google.com/issues/119944680

https://stackoverflow.com/questions/53468190/android-keystore-usernotauthenticatedexception-infinite-loop

https://stackoverflow.com/questions/47920995/infinite-loop-using-androidkeystore-authentication

**Comment by rafaelekol** [comment]
Seems that removing Screen Lock and then setting it again helps to app to work again. If this is the case, we should debug Keystore usage, and fix the issue.

**Comment by esengulov** [comment]
no longer reproducible, closing!
