### ISSUE TITLE
Guest module: several actions should not be triggered at once

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/bank-wallet-android#326]
If I click "New wallet" button it takes time to proceed. BUT I can also click "Restore wallet" button at this time and in this case Restore controller is opened along with the Backup controller.
When any action is triggered and it takes time to proceed - all other actions should be blocked or ignored.

**Comment by rafaelekol** [comment]
By debugging the issue the source of problem seems to happen in creating and starting Kits in MainThread (in WalletManager method initWallets())
