### ISSUE TITLE
Transactions Tab: further UI Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#349]
@TalgatNurdinov add all relevant tasks based on similar issue in iOS repository, https://github.com/horizontalsystems/bank-wallet-ios/issues/188

**Comment by esengulov** [comment]
please upload design with requested changes, you did it for iOS but not for Android
https://github.com/horizontalsystems/bank-wallet-ios/issues/188

**Comment by TalgatNurdinov** [comment]
<img width="511" alt="screen shot 2018-12-18 at 5 07 30 pm" src="https://user-images.githubusercontent.com/42367908/50150234-8135d300-02e7-11e9-9ac0-f9a5e92c84b5.png">

https://zpl.io/VKK0Mm6

**Comment by TalgatNurdinov** [comment]
- [ ] update tabs design 
- [ ] Use coins short name in tab bar on transactions
- [ ] New status indicators
- [ ] Swap currencies 

<img width="366" alt="screen shot 2018-12-24 at 3 37 39 pm" src="https://user-images.githubusercontent.com/42367908/50396108-e418e580-0791-11e9-8d81-23ac397d37bc.png">
https://zpl.io/bAER3Oq
