### ISSUE TITLE
Implement Full Transaction Info

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#398]
- [x] full tx info design
- [x] should have light and dark mode
- [x] add block explorer "Source"  selection controller (see designs in comments, on Jan 18)
- [x] "Data Provider": should open data source selection controller (design attached below, on January 18'th). 
- [ ] if the given API provides the FEE(in fiat) only in USD, then show that for all currencies. Only the horyzontalsystems.xyz will have values for all currencies.
- [x] for Ethereum blockchain we want extra fields (Gas price, Gas used, Gas limit). These blockchain specific terms should be hardcoded, we will not localize them.
- [ ] if the API doesn't provide data for an item (ex: tx size) then show "..." instead of the value.
- [x] integrate the following APIs as the data providers for "blockchain explorers"
- [x] the Share button should be sharing the website link to that transaction on that public block explorer. 
-- if I am sharing with someone transaction than I am basically sending a link to that transaction on selected block explorer. 
-- test the feature with WhatsApp, Telegram and Facebook messenger. 
-- On successful share the user should return back to transaction info. successful share should display "confirmation" checkmark/alert.

##Blockchain Explorers

BTC 
-http://btc.horizontalsystems.xyz (default) 
 -https://btc.com (https://btc.com/api-doc#General   (no access keys, supposedly no restrictions)
-https://blockexplorer.com/api-ref  (no access keys, supposedly no restrictions)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-//IPFS(coming soon, do not add it now)

  BCH
-http://bch.horizontalsystems.xyz (default)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-//IPFS(coming soon, do not add it now)

 ETH
-http://eth.horizontalsystems.xyz (default)
-https://blockchair.com  (no access keys, supposedly no restrictions)
-https://etherscan.io/apis   (the free key on this API restricted to 5 calls/second. As an option we can ask the user to obtain his own free key(https://etherscan.io/myapikey) and use it. That would require an additional step on our end where user will be asked to add the API Key.
-//IPFS(coming soon, do not add it now)

**Comment by esengulov** [comment]
@tmedetbekov note the updated tasks list in description

**Comment by esengulov** [comment]
@tmedetbekov reopened the issue as the feature isn't fully implemented yet

@TalgatNurdinov upload the slightly updated designs here:

- [ ] source selection for block explorer
- [ ] updated design for full transaction info

**Comment by TalgatNurdinov** [comment]
<img width="780" alt="screen shot 2019-01-18 at 11 56 32 am" src="https://user-images.githubusercontent.com/42367908/51368119-1e1ea280-1b18-11e9-8749-f4c697717311.png">
https://app.zeplin.io/project/5b18ecff68e34a92986b0224/dashboard?seid=5b90faef4e79f19ceb4f2dbc

https://app.zeplin.io/project/5b18ecff68e34a92986b0224/dashboard?seid=5b90faef4e79f19ceb4f2dbc

<img width="247" alt="screen shot 2019-01-18 at 12 05 45 pm" src="https://user-images.githubusercontent.com/42367908/51368404-7013f800-1b19-11e9-9b49-c1629bbb7664.png">
https://zpl.io/VxRPyYg

for ETH
<img width="369" alt="screen shot 2019-01-18 at 12 06 40 pm" src="https://user-images.githubusercontent.com/42367908/51368420-8752e580-1b19-11e9-8cea-9d21b2bf8248.png">
