### ISSUE TITLE
Enable user to choose which Blockchain Explorer to use

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#409]
- [x] design selection setting. Should be somewhere in Settings.
- [x] once done create a new issue for implementation
- [ ] @Dianaaiym add localizable text strings

**Comment by esengulov** [comment]
@TalgatNurdinov please upload for android

**Comment by TalgatNurdinov** [comment]
<img width="538" alt="screen shot 2018-12-27 at 7 19 44 pm" src="https://user-images.githubusercontent.com/42367908/50481838-e5564680-0a0d-11e9-9e64-61650dbe1613.png">
https://zpl.io/adrpoR5

**Comment by TalgatNurdinov** [comment]
<img width="779" alt="screen shot 2019-01-18 at 11 40 43 am" src="https://user-images.githubusercontent.com/42367908/51367674-ed3d6e00-1b15-11e9-8690-9c3684782833.png">

https://app.zeplin.io/project/5b18ecff68e34a92986b0224/dashboard?seid=5b48852594d8f6ef1a86adeb
