### ISSUE TITLE
Home Page / Transactions tab: Rounded Value Amounts

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#467]
Update: This issue was reopened. Refer to updated task list, https://github.com/horizontalsystems/bank-wallet-android/issues/467#issuecomment-464680460

**Balance Tab**

- [x] coin balance above $100 then show amount without cents. if below 100$ dollars then show with cents.
- [x] crypto balance: 
-- if coin crypto amount smaller than 0.0001, then show crypto balance in full (8 decimal points)
-- if crypto amount bigger than 0.0001, then show balance only with 4 decimal points.
-- always remove trailing zeros (ex: 1.1000 should be 1.1)

 **Transactions tab**

- [x] same logic applies to both fiat and crypto currency amounts as on Balance tab
- [x] Transactions info: should be displaying real numbers, both for crypto and fiat.

<img width="363" alt="screen shot 2019-01-07 at 10 42 08 am" src="https://user-images.githubusercontent.com/42367908/50749410-e63a7400-1268-11e9-99b8-ca9f7306807d.png">
https://zpl.io/aBNXk8e

**Comment by TalgatNurdinov** [comment]
some adjustments to the logic after further testing:

## Balance Tab

- [ ] header total balance(base currency): show always in full, with decimals.
- [ ] use exact amount for each available coin (not rounded amount) when calculating the total balance

**Base Currency Values** 

- [ ] if balance (in base currency) is smaller or equal 0.01
-- fiat currency balance for that coin should be shown as < 0.01.

- [ ] if coin balance (in base currency) is between 0.01 < X < 1000
-- fiat currency balance for that coin should be shown with cents

- [ ] if coin balance (in base currency) is bigger than 1000
-- fiat currency balance for that coin should be shown without cents

- [ ] same logic for exchange rates

**Crypto Currency Values** 

- [ ] if balance (in crypto) is smaller or equal 0.01
-- show crypto balance with 8 decimal points.

- [ ] if coin balance (in crypto) is bigger 0.01
-- show crypto balance with 4 decimal points

- [ ] always remove trailing zeros (ex: 1.1000 should be 1.1)

## Transactions tab

- [ ] same logic applies to both fiat and crypto currency amounts as on Balance tab

## Transactions  info

- [ ] should be displaying real numbers, both for crypto and fiat.

## Send Controller / Send Confirmation

- [ ] fee: if base currency equivalent for fee is below 0.01, then it should be shown as < 0.01.
- [ ] all other value (amount being sent + base currency equivalent) should be shown in full.

**Comment by esengulov** [comment]
@rafaelekol reopened the issue, updated the tasks list

**Comment by esengulov** [comment]
@rafaelekol one minor issue was provided incorrectly. please apply the fix accordingly
