### ISSUE TITLE
In Light Mode: the initial background that's briefly shown on App Start should be light colored

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#468]
In the dark mode the initial background matches the background of the controllers in the app and as a result the app start process looks visually pleasing. 

On switch to the light mode, the background on start remains dark but the bg in app controllers changes and this results in not so elegant app start :) Needs fix!

**Comment by abdrasulov** [comment]
The app starts with the default theme set in the manifest file that is dark. Then it switches to the light theme if required. We cannot switch theme on startup. As a solution, we can use some background at startup for both themes. TBD.

**Comment by esengulov** [comment]
> The app starts with the default theme set in the manifest file that is dark. Then it switches to the light theme if required. We cannot switch theme on startup.

ok, consider it done in that case
