### ISSUE TITLE
Show Text "Pending" (before icon) on Transaction Info Controller

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#483]
At the moment it's not clear to the user, what happens to the Transactions. It seems like a bug

**Comment by TalgatNurdinov** [comment]
<img width="246" alt="screen shot 2019-01-14 at 1 44 21 pm" src="https://user-images.githubusercontent.com/42367908/51100950-b1976100-1802-11e9-853b-bd1f697c0bd3.png">

https://zpl.io/a755PAY

**Comment by rafaelekol** [comment]
Fixed by #514
