### ISSUE TITLE
Fix rounding in ALL cases

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/bank-wallet-android#498]
Small values always are shown as $0 in transactions. Tests are required!

**Comment by esengulov** [comment]
@TalgatNurdinov @abdrasulov to fix this issue I propose to round the amount below one cent to "one cent".

In other words if the user sends/receives the transaction where the amount is below the 0.01 (base currency unit) then the value should always be rounded to 0.01(in base currency)
