### ISSUE TITLE
after the user clicks on send in "send confirm" the app returns to send controller. there is a delay before it's collapsed. It should collapse right after SEND is clicked

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#539]

**Comment by Dianaaiym** [comment]
only for ETH (no issues for other currencies)

**Comment by abdrasulov** [comment]
This issue is reproduced only when sending ETH. The reason is that app sends ETH via http request and it waits for a response.

We will work on this issue in the upcoming milestone.

**Comment by esengulov** [comment]
Issue Merged Into 
https://github.com/horizontalsystems/bank-wallet-android/issues/667
