### ISSUE TITLE
Switch language/light mode takes quite long time

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#578]
Animation when transitioning to new window  (switch language, switch light mode) is not smooth and glitchy.
Smooth fade animation should be implemented for cases above.

**Comment by rafaelekol** [comment]
We are restarting activity to apply language or theme changes, thus it can take time to relaunch screens.
On powerful phones transition almost instant, on slower phones user see a bit black screen. Since this action is very rare for users, I think current realization is admittable.
