### ISSUE TITLE
Balance Tab: adjust UX for blockchain sync logic

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#636]
same requirements as for the iOS client. Not posting the actual task list here as the requirements for iOS are work in progress and may change by the time we get to implement this in Android. 

stay tuned: https://github.com/horizontalsystems/bank-wallet-ios/issues/402

**Comment by TalgatNurdinov** [comment]
- [ ] Donut behind progress spinner (pressedgrey color on both mode)
- [ ] Bars color spinner on light mode
- [ ] If possible, use new text styles

<img width="755" alt="screen shot 2019-02-13 at 4 11 07 pm" src="https://user-images.githubusercontent.com/42367908/52706274-2d75fc00-2faf-11e9-832c-1ad4d6c80c77.png">
