### ISSUE TITLE
Transaction cells design fixing

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#655]
- [x] Add new text styles with colors
- [ ] Add new color styles
- [x] Replace icons
- [x] Change paddings

! ignore top divider line for now !

Component specs in https://zpl.io/2yzQG7q

**Comment by TalgatNurdinov** [comment]
FYI: I'm created a new project "Android Bank Wallet" in zeplin for Android UI refactoring where included texts, color styles, components and color pairs for dark/light modes

**Comment by TalgatNurdinov** [comment]
- [ ] Change text style of date
- [ ] Remove "-+" symbols from cryptocurrency amount. Only outgoing transaction on fiat currency should be "-" symbol

**Comment by rafaelekol** [comment]
Without rates, it's not clear whether transaction is incoming or outgoing. We need to show negative sign on coins too.
