### ISSUE TITLE
TX info controller: minor updates to layout

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#670]
Following items should be added:

@rafaelekol 

- [x] add coin name
- [x] add exchange rate(base currency) on the date fo transaction. On the rate cell use coin symbol instead of coin name.
- [x] transaction status (bars) and before the transaction is confirmed. Show "CONFIRMED [checkmark]" after it's confirmed. "Confirmed" text should be localizable.
- [x] show only to field for outgoing payments and from field for incoming payments. 
- [x] in some cases from/to fields will not be known, think about how to handle such cases. On some blockchains both sender/recipient or one of them is anonymous. Our controller should be flexible for such use cases.
- [x] instead of “more” show “verify”

@TalgatNurdinov 

- [ ] to/from may be unknown. Such behavior is rather common on some blockchains. Therefore we should have a case when To/From not known or delibertely anonymous (Monero, Zcash, Dash Private Send etc). 
- [ ]  add coin name. the recommended version with the coin name on the rate will not work for cases when the coin name is long such as "Basic Attention Token". Therefore think of some other placement. That said, the rate cell should show coin symbol, not the name.

@Dianaaiym 

- [ ] add key for “Verify”
- [ ] add key for “CONFIRMED”
- [ ] add key for “Historical Rate”

**Comment by TalgatNurdinov** [comment]
instead coin name included coin symbol. i think that enough for identifying

<img width="546" alt="screen shot 2019-03-05 at 3 17 20 pm" src="https://user-images.githubusercontent.com/42367908/53794243-ccac6480-3f59-11e9-9b38-99e77868ed2c.png">

https://zpl.io/bJ7gA0J
