### ISSUE TITLE
Issue with sending/receiving  ETH and ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#687]
- [ ] Send Controller: After the user clicks on send in "Send confirm", the balance should be changed
- [ ] Receive: Unconfirmed transactions for ETH and ERC20, these transactions should observe they protocol for unconfirmed transactions. In other words the transaction affects balance only after it’s confirmed. In the same way not possible to use pending funds for new transactions.
- [ ] When sending ERC20 Tokens the transaction is duplicated

**Comment by Dianaaiym** [comment]
When sending ERC20 Tokens the transaction is duplicated

**Comment by rafaelekol** [comment]
Fixed by #709
