### ISSUE TITLE
Full Transaction Info:  Impossible to change Source(blockexplorer) to Etherscan.io

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#689]
Relevant only to ERC20 Tokens

**Comment by Dianaaiym** [comment]
on device Huawei P8 lite: BlockChair.com is always offline and user can't see Full Transaction Info

**Comment by Dianaaiym** [comment]
on device Huawei P8 lite: BlockChair.com is always offline and user can't see Full Transaction Info
Relevant to ETH and ERC20

**Comment by tmedetbekov** [comment]
@Dianaaiym seems like it's SSL handshake error on Android N/7.0, details here: https://stackoverflow.com/a/42047877/538274
