### ISSUE TITLE
Full Transaction Info : Bugs & Minor Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#690]
- [x] move the source cell to the very first spot on the. it should appear as the first cell (in its own block). Below it will come another bloc with tx data (hash, time etc). leave some space between these two blocks.
- [x] remove the unit "Gwei" where the gas limit is shown

- [x] for ERC20 tokens, show the amount transacted (ex: 3 BNB) in value field. At the moment it shows 0 ETH. That info will be shown only on block explorers that return the the token transferred amount. These are etherscan and horsys.xyz

- [x] for ERC20 tokens, show the additional cell called "Token" above the "To and  "From" cells. it should display the address of the smart contract on ETH blockchain. @TalgatNurdinov will provide the icon that will appear next to the address in the label.

- [ ] timestamp is missing when etherscan used as source

- [ ] make sure that horsys block explorer works. it should be already online by this time

**Comment by tmedetbekov** [comment]
Close by #707

Two tasks not implemented:

* Etherscan does not return `timestamp` value
* Horsys explorer seems like not synced yet

**Comment by Dianaaiym** [comment]
Need to make text changes

**Comment by esengulov** [comment]
@tmedetbekov reopened the issue as changing source for ETH transaction doesn't work. as a result not able to change the problem.

**Comment by tmedetbekov** [comment]
Can you please provide some logs or screens because it works to me, I have tested on several devices

**Comment by esengulov** [comment]
> @esengulov can you please provide some logs or screens because it works to me, I have tested on several devices

my bad, was testing the issue before that in flight mode and forgot to turn it back off :(
