### ISSUE TITLE
Design Transaction fee Adjustment

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#713]
I am thinking we should start with three values: low, normal, priority. it should appear in send confirmation controller.

At the same time should be compatible with various blockchains that may have zero or standard fee rates

**Comment by TalgatNurdinov** [comment]
https://zpl.io/beDKk7Y
<img width="244" alt="screen shot 2019-02-28 at 6 46 15 pm" src="https://user-images.githubusercontent.com/42367908/53567596-e892bd80-3b89-11e9-84ae-1badcce6146d.png">
