### ISSUE TITLE
Apply Android Design Enhancements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#736]
Get the parent pages (Balance, Transactions, Settings) on Android and iOS to looks as similar as possible (colors, icons, fonts, ratios and other elements on the page)

**Comment by TalgatNurdinov** [comment]
** Cells 
- [ ] Input
       Single Line
       Multi line
       - [ ] Font Styles
       - [ ] Buttons
       - [ ] Errors

- [ ] Cells 
       Single Line
       Multi line
       - [ ] Font Styles
       - [ ] Accessories
       - [ ] Dividers

- [ ] Header / Footer 
       Light/Dark

- [ ] Nav Bars
       App Bar
       Tab / Amount / Hash bar
       Botton bar
       - [ ] Font Styles
       - [ ] Icons
       - [ ] Dividers

 - [ ] Controllers
         Confirm
         Receive
         Send
         Send Confirm
         - [ ] Font Style
         - [ ] Icons 
         - [ ] New cells

**Comment by TalgatNurdinov** [comment]
- [ ] Coin Manager screen cells
- [ ] Wrong disabled Confirm button on confirm controller with checkbox
- [ ] Wrong disabled Confirm button on unlink
- [ ] Disabled switch button on send controller (style - steel20)
