### ISSUE TITLE
Design Lightning Network for BTC

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#737]

**Comment by esengulov** [comment]
@TalgatNurdinov status?

**Comment by TalgatNurdinov** [comment]
<img width="364" alt="Screen Shot 2019-03-13 at 2 16 10 PM" src="https://user-images.githubusercontent.com/42367908/54263243-96469900-459a-11e9-8fe9-1dcfb0ab76bc.png">

**Comment by esengulov** [comment]
looks good!
