### ISSUE TITLE
Layout requirements for Send Controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#741]
As we integrate new blockchains(Dahs, Litecoin, Nano, Monero etc) and token standards (i.e. ERC20) we are going to encounter different options/capabilities for sending tokens on that blockchain. 

For instance, Dash blockchain enables users to send regular transactions as well as "private" and "instant" transactions on demand. That means that send controller for Dash blockchain should take into account the ability for the user to interact with these additional options in the interface.

Furthermore, some blockchains don't have the transactions fees at all, or have a constant transaction fee. The send controller we provide should be flexible and be compatible with such requirements

Therefore, review Send Controller and ensure that it's compatibly with these requirements

- [ ] some blockchains have "0" or fixed transaction fees
- [ ] some blockchains may provide additional features i.e. 
-- anonymous transactions
-- fast/priority transactions

**Comment by esengulov** [comment]
@TalgatNurdinov For this issue I would like to see 4 variants of existing send controller

1. variable fee*
2. fixed fee*
3. no fee*
4. when currency in question comes with additional capabilities like "private send" or "instant send". Dash is going to be the first blockchain that we integrate that has such capabilities. Therefore, it should be taken into account.

*note: these are mutually exclusive options. In other words only one of three can apply to a given blockchain.

**Comment by TalgatNurdinov** [comment]
variable fee* - https://zpl.io/beDKk7Y
fixed fee* no fee* - https://zpl.io/adpw8z7
private send / instant send - https://zpl.io/29OLdEz
