### ISSUE TITLE
New Wallet - Change Disclaimer Texts

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#742]
- [x] I understand that I am a sole owner of a private 12-word Secret Key which is securely stored on my phone and enables me to control funds on my wallet.

- [x] I understand that if this app is ever moved, deleted or malfunctions, the access to my wallet can be only recovered with that Secret Key.

- [ ] I understand that changing the phone unlock PIN or deleting app data in Android settings deletes the Secret Key from device. I would need to provide my Secret Key to the app in order to regain access to my wallet after that.

- [x] I understand that developers of this app can not be held responsible for any unintended bugs or issues that may arise while using this app.

**Comment by Dianaaiym** [comment]
update texts
