### ISSUE TITLE
Add New ERC20 Tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#743]
- [x] Aurora DAO
-- contract address: 0xcdcfc0f66c522fd086a1b725ea3c0eeb9f9e8814  
-- AURA

- [x] EnjinCoin
-- contract address: 0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c 
-- ENJ

- [x] WAX Token
-- contract address:  0x39Bb259F66E1C59d5ABEF88375979b4D20D98022
-- WAX

- [x] IDEX Membership
--contract address: 0xcc13fc627effd6e35d2d2706ea3c4d7396c610ea
--  IDXM

- [x] @TalgatNurdinov please attach icons for these coins (for Android)

**Comment by rafaelekol** [comment]
@esengulov also we need tokens shortcode

**Comment by esengulov** [comment]
> @esengulov also we need tokens shortcode

these details are available in the token contract itself, you may also look it up on Etherscan.io

fot instance, here is the Enjin Coin overview, https://etherscan.io/address/0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c#readContract

The lower section of the page lists all contract parameters including name and symbol

**Comment by TalgatNurdinov** [comment]
coin icons  - https://zpl.io/br8P0XW

**Comment by Dianaaiym** [comment]
refer to iOS version for reference
