### ISSUE TITLE
Add custom text for Authorization Required Screen 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#782]
![IMG_1620](https://user-images.githubusercontent.com/22589457/55212188-fedb7a00-5218-11e9-89ba-904a4016d64d.jpg)

**Comment by Dianaaiym** [comment]
need to replace text

**Comment by esengulov** [comment]
> need to replace text

Use following texts on that controller:

- **title** : Phone PIN
- **description** : This app requires your phone's PIN in order to keep sensitive data from your wallet in Android's secure storage and not in the app itself.
