### ISSUE TITLE
Send Module should validate Address and Amount

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android#83]
- [ ] Send Button should only get activated when amount and address are both have valid entries.
- [ ] display balance for the coin in the send module 
- [ ] show text error just under input in red color. Also set red border for invalid input
- [ ] validate entered address
- [ ] validate input on amount field
- [ ] add the switch(base currency <>crypto) button back to the amount field 
- [ ] instead "not available amount' show available balance

<img width="248" alt="screen shot 2018-11-07 at 1 54 06 pm" src="https://user-images.githubusercontent.com/42367908/48117834-a1a85180-e294-11e8-84c7-02fe23b677b1.png">

https://zpl.io/2EKoGzM

**Comment by esengulov** [comment]
> @TalgatNurdinov add coin's balance to the send controller. it needs to be easily available to the sender when sending funds

what's the status on this?

**Comment by esengulov** [comment]
moved to another issue https://github.com/horizontalsystems/bank-wallet-android/issues/262
