### ISSUE TITLE
Add new ERC20 Tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/bank-wallet-android#841]
- [x] Holo (HOT)
contract address: 0x6c6EE5e31d828De241282B9606C8e98Ea48526E2

- [x] Cypto.com chain (CRO)
contract address: 0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b

- [x] IOST
contract address: 0xFA1a856Cfa3409CFa145Fa4e20Eb270dF3EB21ab

- [x] Loopring (LRC)
contract address: 0xEF68e7C694F40c8202821eDF525dE3782458639f

- [x] aelf (ELF)
contract address: 0xbf2179859fc6D5BEE9Bf9158632Dc51678a4100e

- [x] orbs (ORBS)
contract address: 0xff56Cc6b1E6dEd347aA0B7676C85AB0B3D08B0FA

- [x] @TalgatNurdinov please attach icon for this coin

**Comment by TalgatNurdinov** [comment]
[erc20icons.andr.26.04.zip](https://github.com/horizontalsystems/bank-wallet-android/files/3119874/erc20icons.andr.26.04.zip)
