### ISSUE TITLE
Database Migration : on wallet restore ERC20 tokens show balances from previous wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#846]
It looks like UNLINK FROM THIS DEVICE doesn't work correctly for ERC20 tokens

To reproduce:

1. download a new build and restore some wallet that has some ERC20 tokens with non-zero balance
2. unlink the wallet from device
3. restore some other wallet.
4. you will notice that balance s for erc20 tokens would be shown from previous wallet.

**Comment by rafaelekol** [comment]
Moved this ticket to [Ethereum Kit Project](https://github.com/horizontalsystems/ethereum-kit-android/issues/64)
