### ISSUE TITLE
prepare Play Market listing for Bank Wallet

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#85]

**Comment by IzzySoft** [comment]
Also consider [F-Droid](https://f-droid.org/) :wink:

**Comment by esengulov** [comment]
> Also consider [F-Droid](https://f-droid.org/) 😉

will do! :)

**Comment by esengulov** [comment]
> No prob. Ping me if you need help with F-Droid (disclosure: I'm one of the maintainers there meanwhile 😉)

noted!

**Comment by esengulov** [comment]
@Dianaaiym use the contents of README file (link below) for Play Market description

https://github.com/horizontalsystems/bank-wallet-android/edit/master/README.md

**Comment by IzzySoft** [comment]
Umm... closed means you want to get it listed in F-Droid now – or you don't want to? I'm a bit confused now.

**Comment by IzzySoft** [comment]
@esengulov @rafaelekol @tmedetbekov ???
