### ISSUE TITLE
Transaction Info (incl. expanded mode: Full Transaction Info)

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-android#88]
- [ ] the amount field should not show "-" signs on outgoing transactions.
- [ ] The share buttons should share permanent IPFS permalink to transaction record

![status pending](https://user-images.githubusercontent.com/42367908/45355813-353a0a80-b5e3-11e8-9211-a84f74174ea5.png)
![status processing](https://user-images.githubusercontent.com/42367908/45355812-353a0a80-b5e3-11e8-9e0a-4a8416a180b7.png)
![status scroll](https://user-images.githubusercontent.com/42367908/45355814-35d2a100-b5e3-11e8-807e-11ca89a1580c.png)
![status completed](https://user-images.githubusercontent.com/42367908/45355815-35d2a100-b5e3-11e8-80fb-5d7d4bee94d0.png)

https://zpl.io/agNYn1R
https://zpl.io/agNYn1D
https://zpl.io/bPmGdNx
https://zpl.io/Vknqm9L

**Comment by esengulov** [comment]
@TalgatNurdinov provide latest design mockups for Android. We have finished this for iOS (
https://github.com/horizontalsystems/bank-wallet-ios/issues/232 ) but not for Android

**Comment by TalgatNurdinov** [comment]
<img width="1039" alt="screen shot 2018-12-20 at 12 05 35 pm" src="https://user-images.githubusercontent.com/42367908/50266906-ad6c6380-044f-11e9-8acf-6cbc65140315.png">

https://app.zeplin.io/project/5b18ecff68e34a92986b0224/dashboard?seid=5b90faef4e79f19ceb4f2dbc

**Comment by esengulov** [comment]
@TalgatNurdinov good!
